services:
  backend:
    image: educational_backend
    container_name: backend
    env_file:
      - ./.env/backend.env
    ports:
      - "5000:5000"

  frontend:
    image: educational_frontend
    container_name: frontend
    ports:
      - "4200:80"
    env_file:
      - ./.env/frontend.env
    depends_on:
      - backend
