name: Educational CD

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]
    
env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  BACKEND_REPO_NAME: ${{secrets.BACKEND_REPO_NAME}}
  FRONTEND_REPO_NAME: ${{secrets.FRONTEND_REPO_NAME}}
  SSH_HOST: ${{secrets.SSH_HOST}}
  SSH_USERNAME: ${{secrets.SSH_USERNAME}}
  SSH_KEY: ${{secrets.SSH_KEY}}
  

jobs:
  cd:
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: $SSH_HOST
          username: $SSH_USERNAME
          key: $SSH_KEY
          script: |
            docker compose down
            docker compose up -d --force-recreate
